const countryData = [
    { name: "Afghanistan", code: "AF", dialCode: "93" },
    { name: "Albanie", code: "AL", dialCode: "355" },
    { name: "Algérie", code: "DZ", dialCode: "213" },
    { name: "Andorre", code: "AD", dialCode: "376" },
    { name: "Angola", code: "AO", dialCode: "244" },
    { name: "Argentine", code: "AR", dialCode: "54" },
    { name: "Arménie", code: "AM", dialCode: "374" },
    { name: "Australie", code: "AU", dialCode: "61" },
    { name: "Autriche", code: "AT", dialCode: "43" },
    { name: "Azerbaïdjan", code: "AZ", dialCode: "994" },
    { name: "Bahamas", code: "BS", dialCode: "1" },
    { name: "Bahreïn", code: "BH", dialCode: "973" },
    { name: "Bangladesh", code: "BD", dialCode: "880" },
    { name: "Barbade", code: "BB", dialCode: "1" },
    { name: "Bélarus", code: "BY", dialCode: "375" },
    { name: "Belgique", code: "BE", dialCode: "32" },
    { name: "Belize", code: "BZ", dialCode: "501" },
    { name: "Bénin", code: "BJ", dialCode: "229" },
    { name: "Bhoutan", code: "BT", dialCode: "975" },
    { name: "Bolivie", code: "BO", dialCode: "591" },
    { name: "Bosnie-Herzégovine", code: "BA", dialCode: "387" },
    { name: "Botswana", code: "BW", dialCode: "267" },
    { name: "Brésil", code: "BR", dialCode: "55" },
    { name: "Brunei", code: "BN", dialCode: "673" },
    { name: "Bulgarie", code: "BG", dialCode: "359" },
    { name: "Burkina Faso", code: "BF", dialCode: "226" },
    { name: "Burundi", code: "BI", dialCode: "257" },
    { name: "Côte d'Ivoire", code: "CI", dialCode: "225" },
    { name: "Cabo Verde", code: "CV", dialCode: "238" },
    { name: "Cambodge", code: "KH", dialCode: "855" },
    { name: "Cameroun", code: "CM", dialCode: "237" },
    { name: "Canada", code: "CA", dialCode: "1" },
    { name: "République centrafricaine", code: "CF", dialCode: "236" },
    { name: "Tchad", code: "TD", dialCode: "235" },
    { name: "Chili", code: "CL", dialCode: "56" },
    { name: "Chine", code: "CN", dialCode: "86" },
    { name: "Colombie", code: "CO", dialCode: "57" },
    { name: "Comores", code: "KM", dialCode: "269" },
    { name: "Congo (Brazzaville)", code: "CG", dialCode: "242" },
    { name: "Congo (RDC)", code: "CG", dialCode: "243" },
    { name: "Costa Rica", code: "CR", dialCode: "506" },
    { name: "Croatie", code: "HR", dialCode: "385" },
    { name: "Cuba", code: "CU", dialCode: "53" },
    { name: "Chypre", code: "CY", dialCode: "357" },
    { name: "Tchéquie", code: "CZ", dialCode: "420" },
    { name: "Danemark", code: "DK", dialCode: "45" },
    { name: "Djibouti", code: "DJ", dialCode: "253" },
    { name: "Dominique", code: "DM", dialCode: "1" },
    { name: "République dominicaine", code: "DO", dialCode: "1" },
    { name: "Équateur", code: "EC", dialCode: "593" },
    { name: "Égypte", code: "EG", dialCode: "20" },
    { name: "Salvador", code: "SV", dialCode: "503" },
    { name: "Guinée équatoriale", code: "GQ", dialCode: "240" },
    { name: "Érythrée", code: "ER", dialCode: "291" },
    { name: "Estonie", code: "EE", dialCode: "372" },
    { name: "Eswatini", code: "SZ", dialCode: "268" },
    { name: "Éthiopie", code: "ET", dialCode: "251" },
    { name: "Fidji", code: "FJ", dialCode: "679" },
    { name: "Finlande", code: "FI", dialCode: "358" },
    { name: "France", code: "FR", dialCode: "33" },
    { name: "Gabon", code: "GA", dialCode: "241" },
    { name: "Gambie", code: "GM", dialCode: "220" },
    { name: "Géorgie", code: "GE", dialCode: "995" },
    { name: "Allemagne", code: "DE", dialCode: "49" },
    { name: "Ghana", code: "GH", dialCode: "233" },
    { name: "Grèce", code: "GR", dialCode: "30" },
    { name: "Grenade", code: "GD", dialCode: "1" },
    { name: "Guatemala", code: "GT", dialCode: "502" },
    { name: "Guinée", code: "GN", dialCode: "224" },
    { name: "Guinée-Bissau", code: "GW", dialCode: "245" },
    { name: "Guyana", code: "GY", dialCode: "592" },
    { name: "Haïti", code: "HT", dialCode: "509" },
    { name: "Honduras", code: "HN", dialCode: "504" },
    { name: "Hongrie", code: "HU", dialCode: "36" },
    { name: "Islande", code: "IS", dialCode: "354" },
    { name: "Inde", code: "IN", dialCode: "91" },
    { name: "Indonésie", code: "ID", dialCode: "62" },
    { name: "Iran", code: "IR", dialCode: "98" },
    { name: "Irak", code: "IQ", dialCode: "964" },
    { name: "Irlande", code: "IE", dialCode: "353" },
    { name: "Israël", code: "IL", dialCode: "972" },
    { name: "Italie", code: "IT", dialCode: "39" },
    { name: "Jamaïque", code: "JM", dialCode: "1" },
    { name: "Japon", code: "JP", dialCode: "81" },
    { name: "Jordanie", code: "JO", dialCode: "962" },
    { name: "Kazakhstan", code: "KZ", dialCode: "7" },
    { name: "Kenya", code: "KE", dialCode: "254" },
    { name: "Kiribati", code: "KI", dialCode: "686" },
    { name: "Koweït", code: "KW", dialCode: "965" },
    { name: "Kirghizistan", code: "KG", dialCode: "996" },
    { name: "Laos", code: "LA", dialCode: "856" },
    { name: "Lettonie", code: "LV", dialCode: "371" },
    { name: "Liban", code: "LB", dialCode: "961" },
    { name: "Lesotho", code: "LS", dialCode: "266" },
    { name: "Libéria", code: "LR", dialCode: "231" },
    { name: "Libye", code: "LY", dialCode: "218" },
    { name: "Liechtenstein", code: "LI", dialCode: "423" },
    { name: "Lituanie", code: "LT", dialCode: "370" },
    { name: "Luxembourg", code: "LU", dialCode: "352" },
    { name: "Madagascar", code: "MG", dialCode: "261" },
    { name: "Malawi", code: "MW", dialCode: "265" },
    { name: "Malaisie", code: "MY", dialCode: "60" },
    { name: "Maldives", code: "MV", dialCode: "960" },
    { name: "Mali", code: "ML", dialCode: "223" },
    { name: "Malte", code: "MT", dialCode: "356" },
    { name: "Îles Marshall", code: "MH", dialCode: "692" },
    { name: "Mauritanie", code: "MR", dialCode: "222" },
    { name: "Maurice", code: "MU", dialCode: "230" },
    { name: "Mexique", code: "MX", dialCode: "52" },
    { name: "Micronésie", code: "FM", dialCode: "691" },
    { name: "Moldavie", code: "MD", dialCode: "373" },
    { name: "Monaco", code: "MC", dialCode: "377" },
    { name: "Mongolie", code: "MN", dialCode: "976" },
    { name: "Monténégro", code: "ME", dialCode: "382" },
    { name: "Maroc", code: "MA", dialCode: "212" },
    { name: "Mozambique", code: "MZ", dialCode: "258" },
    { name: "Myanmar (Birmanie)", code: "MM", dialCode: "95" },
    { name: "Namibie", code: "NA", dialCode: "264" },
    { name: "Nauru", code: "NR", dialCode: "674" },
    { name: "Népal", code: "NP", dialCode: "977" },
    { name: "Pays-Bas", code: "NL", dialCode: "31" },
    { name: "Nouvelle-Zélande", code: "NZ", dialCode: "64" },
    { name: "Nicaragua", code: "NI", dialCode: "505" },
    { name: "Niger", code: "NE", dialCode: "227" },
    { name: "Nigéria", code: "NG", dialCode: "234" },
    { name: "Corée du Nord", code: "KP", dialCode: "850" },
    { name: "Macédoine du Nord", code: "MK", dialCode: "389" },
    { name: "Norvège", code: "NO", dialCode: "47" },
    { name: "Oman", code: "OM", dialCode: "968" },
    { name: "Pakistan", code: "PK", dialCode: "92" },
    { name: "Palaos", code: "PW", dialCode: "680" },
    { name: "Palestine", code: "PS", dialCode: "970" },
    { name: "Panama", code: "PA", dialCode: "507" },
    { name: "Papouasie-Nouvelle-Guinée", code: "PG", dialCode: "675" },
    { name: "Paraguay", code: "PY", dialCode: "595" },
    { name: "Pérou", code: "PE", dialCode: "51" },
    { name: "Philippines", code: "PH", dialCode: "63" },
    { name: "Pologne", code: "PL", dialCode: "48" },
    { name: "Portugal", code: "PT", dialCode: "351" },
    { name: "Qatar", code: "QA", dialCode: "974" },
    { name: "Roumanie", code: "RO", dialCode: "40" },
    { name: "Russie", code: "RU", dialCode: "7" },
    { name: "Rwanda", code: "RW", dialCode: "250" },
    { name: "Saint-Kitts-et-Nevis", code: "KN", dialCode: "1" },
    { name: "Sainte-Lucie", code: "LC", dialCode: "1" },
    { name: "Saint-Vincent-et-les-Grenadines", code: "VC", dialCode: "1" },
    { name: "Samoa", code: "WS", dialCode: "685" },
    { name: "Saint-Marin", code: "SM", dialCode: "378" },
    { name: "Sao Tomé-et-Principe", code: "ST", dialCode: "239" },
    { name: "Arabie saoudite", code: "SA", dialCode: "966" },
    { name: "Sénégal", code: "SN", dialCode: "221" },
    { name: "Serbie", code: "RS", dialCode: "381" },
    { name: "Seychelles", code: "SC", dialCode: "248" },
    { name: "Sierra Leone", code: "SL", dialCode: "232" },
    { name: "Singapour", code: "SG", dialCode: "65" },
    { name: "Slovaquie", code: "SK", dialCode: "421" },
    { name: "Slovénie", code: "SI", dialCode: "386" },
    { name: "Îles Salomon", code: "SB", dialCode: "677" },
    { name: "Somalie", code: "SO", dialCode: "252" },
    { name: "Afrique du Sud", code: "ZA", dialCode: "27" },
    { name: "Corée du Sud", code: "KR", dialCode: "82" },
    { name: "Soudan du Sud", code: "SS", dialCode: "211" },
    { name: "Espagne", code: "ES", dialCode: "34" },
    { name: "Sri Lanka", code: "LK", dialCode: "94" },
    { name: "Soudan", code: "SD", dialCode: "249" },
    { name: "Suriname", code: "SR", dialCode: "597" },
    { name: "Suède", code: "SE", dialCode: "46" },
    { name: "Suisse", code: "CH", dialCode: "41" },
    { name: "Syrie", code: "SY", dialCode: "963" },
    { name: "Taïwan", code: "TW", dialCode: "886" },
    { name: "Tadjikistan", code: "TJ", dialCode: "992" },
    { name: "Tanzanie", code: "TZ", dialCode: "255" },
    { name: "Thaïlande", code: "TH", dialCode: "66" },
    { name: "Timor-Leste", code: "TL", dialCode: "670" },
    { name: "Togo", code: "TG", dialCode: "228" },
    { name: "Tonga", code: "TO", dialCode: "676" },
    { name: "Trinité-et-Tobago", code: "TT", dialCode: "1" },
    { name: "Tunisie", code: "TN", dialCode: "216" },
    { name: "Turquie", code: "TR", dialCode: "90" },
    { name: "Turkménistan", code: "TM", dialCode: "993" },
    { name: "Tuvalu", code: "TV", dialCode: "688" },
    { name: "Ouganda", code: "UG", dialCode: "256" },
    { name: "Ukraine", code: "UA", dialCode: "380" },
    { name: "Émirats arabes unis", code: "AE", dialCode: "971" },
    { name: "Royaume-Uni", code: "GB", dialCode: "44" },
    { name: "États-Unis", code: "US", dialCode: "1" },
    { name: "Uruguay", code: "UY", dialCode: "598" },
    { name: "Ouzbékistan", code: "UZ", dialCode: "998" },
    { name: "Vanuatu", code: "VU", dialCode: "678" },
    { name: "Vatican", code: "VA", dialCode: "379" },
    { name: "Venezuela", code: "VE", dialCode: "58" },
    { name: "Viêt Nam", code: "VN", dialCode: "84" },
    { name: "Yémen", code: "YE", dialCode: "967" },
    { name: "Zambie", code: "ZM", dialCode: "260" },
    { name: "Zimbabwe", code: "ZW", dialCode: "263" }
  ];
  
  export default countryData;
